### ISSUE TITLE
出错 GPSegFun (line 208)         showPointCloud(pcData(1:3, GrdIdx)', 'g');

### ISSUE THREAD

**Issue by jec1key** [DrGabor/LiDAR#1]
出错 GPSegFun (line 208)
        showPointCloud(pcData(1:3, GrdIdx)', 'g');
文件里没有showPointCloud这个函数

**Comment by DrGabor** [comment]
Hi, the showPointCloud() or pcshow() is the build-in function since Matlab R2015a. Hope it will solve your problem.
