### ISSUE TITLE
Undefined functions or variables 'RecoverRT','ExtensiveRT'.

### ISSUE THREAD

**Issue by b-goose** [DrGabor/LiDAR#2]
未定义函数或变量 'RecoverRT'。

出错 RoPSMatchFun (line 46)
    [R0, T0, tmpError ] = RecoverRT( MovData, RefData, Idx);

出错 main (line 9)
[R0, T0, MaxEvalNum, RefSize] = RoPSMatchFun( rops0, rops1, 1 );

**Comment by DrGabor** [comment]
Hi, I have upload RecoverRT.m and ExtensiveRT.m to the folder of CommonFunctions, please download them.
