### ISSUE TITLE
Is there any way to speed up?

### ISSUE THREAD

**Issue by firesnow1234** [DrGabor/LiDAR#4]
I tested the method of road segmentation in Matlab. It's  a little slow. Is there any way to speed it up? If it's convenient,  could you open the C/C++ code to me for learning. thx

**Comment by DrGabor** [comment]
Hi firesnow, the algorithm is reported to be real-time in the reference[1][2]. Thus, you can implement it with C/C++, and the speed will be 10~20Hz or so.
